package ca.hccis.cis2232.a2.bo;

import ca.hccis.cis2232.a2.data.Booking;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;
import org.junit.jupiter.params.provider.NullAndEmptySource;
import org.junit.jupiter.params.provider.ValueSource;

import static org.junit.jupiter.api.Assertions.assertAll;
import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * AI generated test suite for BookingBO.calculate.
 * <p>
 * Generated by Claude (AI) from the project requirements in the README
 * (room price, equipment rental and birthday add-ons, 15% tax) and the
 * Booking entity class.
 *
 * @author Claude (AI generated)
 * @author Alexander Fendyur (reviewer)
 * @since 2/10/2026
 *
 * @modifiedby Claude (AI) 2026-10-03 Renamed test methods to lowerCamelCase and added a
 * javadoc to each test, per the CIS Programming Standards.
 */
class BookingBOAITest {

    private static final double DELTA = 0.001;

    /**
     * Build a booking for the given room with the given add-ons.
     *
     * @param roomType  the room type name
     * @param birthday  whether it is a birthday booking
     * @param equipment whether equipment is rented
     * @return the new booking
     * @author Claude (AI generated)
     * @since 2/10/2026
     */
    private static Booking booking(String roomType, boolean birthday, boolean equipment) {
        Booking booking = new Booking();
        booking.setRoomType(roomType);
        booking.setBirthday(birthday);
        booking.setEquipmentNeeded(equipment);
        return booking;
    }

    /**
     * Each room type is priced from its base price plus tax.
     *
     * @param roomType the room type name to test
     * @param expectedTotal the expected total including tax
     * @author Claude (AI generated)
     * @author Alexander Fendyur (reviewer)
     * @since 2/10/2026
     */
    @ParameterizedTest(name = "{0} with no extras costs {1}")
    @CsvSource({
            "Party Room,     230.00",
            "Gym,            172.50",
            "Small Rec Room, 115.00"
    })
    @DisplayName("Each room type is priced from its base price plus tax")
    void calculateEachRoomTypeNoExtras(String roomType, double expectedTotal) {
        assertEquals(expectedTotal, BookingBO.calculate(booking(roomType, false, false)), DELTA);
    }

    /**
     * Every combination of birthday and equipment add-ons.
     *
     * @param birthday whether it is a birthday booking
     * @param equipment whether equipment is rented
     * @param expectedTotal the expected total including tax
     * @author Claude (AI generated)
     * @author Alexander Fendyur (reviewer)
     * @since 2/10/2026
     */
    @ParameterizedTest(name = "birthday={0}, equipment={1} costs {2}")
    @CsvSource({
            "false, false, 115.00",
            "true,  false, 172.50",
            "false, true,  143.75",
            "true,  true,  201.25"
    })
    @DisplayName("Every combination of birthday and equipment add-ons")
    void calculateAddOnCombinationsSmallRecRoom(boolean birthday, boolean equipment, double expectedTotal) {
        assertEquals(expectedTotal,
                BookingBO.calculate(booking("Small Rec Room", birthday, equipment)), DELTA);
    }

    /**
     * The total is the subtotal with exactly 15% tax applied.
     *
     * @author Claude (AI generated)
     * @author Alexander Fendyur (reviewer)
     * @since 2/10/2026
     */
    @Test
    @DisplayName("The total is the subtotal with exactly 15% tax applied")
    void calculateAppliesFifteenPercentTax() {
        Booking booking = booking("Gym", true, true);
        double subTotal = BookingBO.PRICE_GYM + BookingBO.BIRTHDAY_COST + BookingBO.EQUIPMENT_COST;

        double total = BookingBO.calculate(booking);

        assertEquals(subTotal * 0.15, total - subTotal, DELTA);
    }

    /**
     * Base price, birthday cost and total are stored on the booking.
     *
     * @author Claude (AI generated)
     * @author Alexander Fendyur (reviewer)
     * @since 2/10/2026
     */
    @Test
    @DisplayName("Base price, birthday cost and total are stored on the booking")
    void calculateStoresPricesOnBooking() {
        Booking booking = booking("Party Room", true, false);

        double total = BookingBO.calculate(booking);

        assertAll(
                () -> assertEquals(BookingBO.PRICE_PARTY_ROOM, booking.getBasePrice(), DELTA),
                () -> assertEquals(BookingBO.BIRTHDAY_COST, booking.getBirthdayCost(), DELTA),
                () -> assertEquals(total, booking.getTotalPrice(), DELTA)
        );
    }

    /**
     * A non-birthday booking has no birthday cost.
     *
     * @author Claude (AI generated)
     * @author Alexander Fendyur (reviewer)
     * @since 2/10/2026
     */
    @Test
    @DisplayName("A non-birthday booking has no birthday cost")
    void calculateNotBirthdayBirthdayCostIsZero() {
        Booking booking = booking("Party Room", false, true);

        BookingBO.calculate(booking);

        assertEquals(0.0, booking.getBirthdayCost(), DELTA);
    }

    /**
     * Recalculating after removing the birthday clears the stale birthday cost.
     *
     * @author Claude (AI generated)
     * @author Alexander Fendyur (reviewer)
     * @since 2/10/2026
     */
    @Test
    @DisplayName("Recalculating after removing the birthday clears the stale birthday cost")
    void calculateRecalculateAfterChangeUpdatesBooking() {
        Booking booking = booking("Gym", true, false);
        BookingBO.calculate(booking);

        booking.setBirthday(false);
        double total = BookingBO.calculate(booking);

        assertEquals(172.50, total, DELTA);
        assertEquals(0.0, booking.getBirthdayCost(), DELTA);
    }

    /**
     * Calculating twice gives the same result.
     *
     * @author Claude (AI generated)
     * @author Alexander Fendyur (reviewer)
     * @since 2/10/2026
     */
    @Test
    @DisplayName("Calculating twice gives the same result")
    void calculateIsRepeatable() {
        Booking booking = booking("Party Room", true, true);

        double first = BookingBO.calculate(booking);
        double second = BookingBO.calculate(booking);

        assertEquals(first, second, DELTA);
    }

    /**
     * Add-ons always make the booking cost more.
     *
     * @author Claude (AI generated)
     * @author Alexander Fendyur (reviewer)
     * @since 2/10/2026
     */
    @Test
    @DisplayName("Add-ons always make the booking cost more")
    void calculateAddOnsIncreaseTotal() {
        double plain = BookingBO.calculate(booking("Gym", false, false));
        double withExtras = BookingBO.calculate(booking("Gym", true, true));

        assertTrue(withExtras > plain);
        assertFalse(plain > withExtras);
    }

    /**
     * Room type matching ignores case and surrounding spaces.
     *
     * @param roomType the room type name to test
     * @author Claude (AI generated)
     * @author Alexander Fendyur (reviewer)
     * @since 2/10/2026
     */
    @ParameterizedTest
    @ValueSource(strings = {"gym", "PARTY ROOM", "  Small Rec Room  "})
    @DisplayName("Room type matching ignores case and surrounding spaces")
    void calculateRoomTypeIsLenient(String roomType) {
        assertDoesNotThrow(() -> BookingBO.calculate(booking(roomType, false, false)));
    }

    /**
     * Missing or unknown room types are rejected.
     *
     * @param roomType the room type name to test
     * @author Claude (AI generated)
     * @author Alexander Fendyur (reviewer)
     * @since 2/10/2026
     */
    @ParameterizedTest
    @NullAndEmptySource
    @ValueSource(strings = {"Hot Tub", "   "})
    @DisplayName("Missing or unknown room types are rejected")
    void calculateInvalidRoomTypeThrows(String roomType) {
        assertThrows(IllegalArgumentException.class,
                () -> BookingBO.calculate(booking(roomType, false, false)));
    }

    /**
     * A null booking is rejected.
     *
     * @author Claude (AI generated)
     * @author Alexander Fendyur (reviewer)
     * @since 2/10/2026
     */
    @Test
    @DisplayName("A null booking is rejected")
    void calculateNullBookingThrows() {
        IllegalArgumentException e = assertThrows(IllegalArgumentException.class,
                () -> BookingBO.calculate(null));
        assertNotNull(e.getMessage());
    }
}
